#!/usr/bin/env Rscript

# 02_fixed_effects_models.R
# Purpose: reproduce the RQ1 fixed-effects grade models and robustness checks.
# Input: processed files generated by scripts/01_prepare_data.R.
# Outputs: CSV summaries under outputs/fe_models/.

source(file.path("R", "00_packages.R"))
source(file.path("R", "00_paths.R"))
source(file.path("R", "utils_io.R"))

message("Project root: ", PROJECT_ROOT)
message("Reading processed data from: ", DATA_PROCESSED)

student_term_file <- file.path(DATA_PROCESSED, "student_term_fe_analysis.csv")
course_term_agg_file <- file.path(DATA_PROCESSED, "course_term_grade_aggregation.csv")

if (!file.exists(student_term_file) || !file.exists(course_term_agg_file)) {
  stop(
    "Processed data not found. Run first: Rscript scripts/01_prepare_data.R",
    call. = FALSE
  )
}

student_term <- readr::read_csv(student_term_file, show_col_types = FALSE) |>
  janitor::clean_names() |>
  dplyr::mutate(
    course_id = as.character(course_id),
    term = as.character(term),
    instructor_id = as.character(instructor_id),
    post_redesign = as.integer(post_redesign)
  )

course_term_from_students <- readr::read_csv(course_term_agg_file, show_col_types = FALSE) |>
  janitor::clean_names() |>
  dplyr::mutate(
    course_id = as.character(course_id),
    term = as.character(term),
    post_redesign = as.integer(post_redesign)
  )

# Keep copies in the FE output folder for reviewers who look there first.
safe_write_csv(student_term, file.path(OUT_FE, "student_term_fe_analysis.csv"))
safe_write_csv(course_term_from_students, file.path(OUT_FE, "course_term_grade_aggregation.csv"))

# Treatment timing diagnostics.
timing_by_term <- student_term |>
  dplyr::group_by(term, term_index) |>
  dplyr::summarise(
    n_students = dplyr::n(),
    n_courses = dplyr::n_distinct(course_id),
    n_pre = sum(post_redesign == 0, na.rm = TRUE),
    n_post = sum(post_redesign == 1, na.rm = TRUE),
    has_both = n_pre > 0 & n_post > 0,
    .groups = "drop"
  ) |>
  dplyr::arrange(term_index)

timing_by_course <- student_term |>
  dplyr::distinct(course_id, term, term_index, post_redesign) |>
  dplyr::group_by(course_id) |>
  dplyr::summarise(
    n_terms = dplyr::n(),
    first_term = term[which.min(term_index)],
    last_term = term[which.max(term_index)],
    first_post_term = ifelse(
      any(post_redesign == 1),
      term[which.min(ifelse(post_redesign == 1, term_index, Inf))],
      NA_character_
    ),
    has_pre = any(post_redesign == 0),
    has_post = any(post_redesign == 1),
    .groups = "drop"
  )

safe_write_csv(timing_by_term, file.path(OUT_FE, "treatment_timing_by_term.csv"))
safe_write_csv(timing_by_course, file.path(OUT_FE, "treatment_timing_by_course.csv"))

# Descriptive pre/post summaries.
desc_prepost <- student_term |>
  dplyr::group_by(redesign_status, post_redesign) |>
  dplyr::summarise(
    n = dplyr::n(),
    grade_mean = mean(final_numeric_grade, na.rm = TRUE),
    grade_sd = stats::sd(final_numeric_grade, na.rm = TRUE),
    olse_mean = mean(olse_overall_mean, na.rm = TRUE),
    olse_sd = stats::sd(olse_overall_mean, na.rm = TRUE),
    .groups = "drop"
  )

course_change <- student_term |>
  dplyr::group_by(course_id, post_redesign) |>
  dplyr::summarise(
    n = dplyr::n(),
    grade_mean = mean(final_numeric_grade, na.rm = TRUE),
    olse_mean = mean(olse_overall_mean, na.rm = TRUE),
    .groups = "drop"
  ) |>
  tidyr::pivot_wider(
    names_from = post_redesign,
    values_from = c(n, grade_mean, olse_mean),
    names_prefix = "post_"
  ) |>
  dplyr::mutate(
    grade_change = grade_mean_post_1 - grade_mean_post_0,
    olse_change = olse_mean_post_1 - olse_mean_post_0
  ) |>
  dplyr::arrange(grade_change)

safe_write_csv(desc_prepost, file.path(OUT_FE, "descriptive_prepost_summary.csv"))
safe_write_csv(course_change, file.path(OUT_FE, "course_level_prepost_changes.csv"))

message("Fitting fixed-effects models.")

# Primary grade models.
m_grade <- fixest::feols(
  final_numeric_grade ~ post_redesign | course_id + term,
  data = student_term,
  cluster = ~ course_id
)

m_grade_z <- fixest::feols(
  final_numeric_grade_z ~ post_redesign | course_id + term,
  data = student_term,
  cluster = ~ course_id
)

models_primary <- list(
  "Course + term FE" = m_grade,
  "Grade z-score outcome" = m_grade_z
)

models_robust <- list(
  "Course + term + instructor" = fixest::feols(
    final_numeric_grade ~ post_redesign | course_id + term + instructor_id,
    data = student_term,
    cluster = ~ course_id
  ),
  "Course-term aggregate" = fixest::feols(
    final_grade_mean ~ post_redesign | course_id + term,
    data = course_term_from_students,
    weights = ~ n_students,
    cluster = ~ course_id
  )
)

# Redesign-feature models.
models_redesign <- list()
comp_terms <- c(
  "post_x_mastery_redesign_z",
  "post_x_social_vicarious_redesign_z",
  "post_x_structural_compliance_redesign_z"
)

if (all(comp_terms %in% names(student_term))) {
  models_redesign[["3 redesign composites"]] <- fixest::feols(
    final_numeric_grade ~ post_redesign + post_x_mastery_redesign_z +
      post_x_social_vicarious_redesign_z + post_x_structural_compliance_redesign_z |
      course_id + term,
    data = student_term,
    cluster = ~ course_id
  )
}

if ("post_x_redesign_intensity_z" %in% names(student_term)) {
  models_redesign[["Overall redesign intensity"]] <- fixest::feols(
    final_numeric_grade ~ post_redesign + post_x_redesign_intensity_z | course_id + term,
    data = student_term,
    cluster = ~ course_id
  )
}

# One-cluster-at-a-time specifications.
cluster_models <- list()
for (k in 1:8) {
  v <- paste0("post_x_cluster_", k, "_delta_z")
  if (v %in% names(student_term) && stats::sd(student_term[[v]], na.rm = TRUE) > 0) {
    cluster_models[[paste0("Cluster ", k)]] <- fixest::feols(
      stats::as.formula(paste0("final_numeric_grade ~ post_redesign + ", v, " | course_id + term")),
      data = student_term,
      cluster = ~ course_id
    )
  }
}

all_models <- c(models_primary, models_robust, models_redesign, cluster_models)

# Tidy coefficient table for all models.
tidy_all <- purrr::imap_dfr(
  all_models,
  ~ broom::tidy(.x, conf.int = TRUE) |>
    dplyr::mutate(model = .y, .before = 1),
  .id = NULL
)

safe_write_csv(tidy_all, file.path(OUT_FE, "project_soar_fe_grade_coefficients.csv"))

# HTML and Excel summaries are optional convenience outputs.
try(
  modelsummary::modelsummary(
    all_models,
    output = file.path(OUT_FE, "project_soar_fe_grade_model_summary.html"),
    stars = TRUE
  ),
  silent = TRUE
)

try(
  writexl::write_xlsx(
    list(
      coefficients = tidy_all,
      prepost_summary = desc_prepost,
      course_changes = course_change,
      timing_by_term = timing_by_term,
      timing_by_course = timing_by_course
    ),
    file.path(OUT_FE, "project_soar_fe_grade_results.xlsx")
  ),
  silent = TRUE
)

# Leave-one-course-out sensitivity for the primary FE model.
message("Running leave-one-course-out FE checks.")

courses <- sort(unique(student_term$course_id))

loo_results <- purrr::map_dfr(courses, function(cc) {
  dat <- student_term |>
    dplyr::filter(course_id != cc)

  fit <- fixest::feols(
    final_numeric_grade ~ post_redesign | course_id + term,
    data = dat,
    cluster = ~ course_id
  )

  broom::tidy(fit, conf.int = TRUE) |>
    dplyr::filter(term == "post_redesign") |>
    dplyr::mutate(dropped_course = cc, n = nrow(dat), .before = 1)
})

safe_write_csv(loo_results, file.path(OUT_FE, "leave_one_course_out_fe.csv"))

loo_summary <- loo_results |>
  dplyr::summarise(
    min_estimate = min(estimate, na.rm = TRUE),
    max_estimate = max(estimate, na.rm = TRUE),
    all_positive = all(estimate > 0, na.rm = TRUE),
    min_p = min(p.value, na.rm = TRUE),
    max_p = max(p.value, na.rm = TRUE)
  )

safe_write_csv(loo_summary, file.path(OUT_FE, "leave_one_course_out_fe_summary.csv"))

# Small-cluster robust inference using clubSandwich CR2/Satterthwaite.
message("Running CR2/Satterthwaite small-cluster check.")

m_grade_lm <- stats::lm(
  final_numeric_grade ~ post_redesign + factor(course_id) + factor(term),
  data = student_term
)

cr2_test <- clubSandwich::coef_test(
  m_grade_lm,
  vcov = "CR2",
  cluster = student_term$course_id,
  test = "Satterthwaite"
)

cr2_post <- cr2_test |>
  as.data.frame() |>
  tibble::rownames_to_column("term") |>
  dplyr::filter(term == "post_redesign")

safe_write_csv(cr2_post, file.path(OUT_FE, "primary_fe_cr2_small_cluster_test.csv"))

message("Fixed-effects workflow complete.")
message("FE outputs written to: ", OUT_FE)
